version: '3.8'

services:
  parcel_db:
    image: mongo:latest
    container_name: parcel-database
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: Pa55w0rd
      MONGO_INITDB_DATABASE: parcels
    volumes:
      - mongodb_data_parcel:/data/db

  user_db:
    image: mongo:latest
    container_name: user-database
    ports:
      - "28018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: Pa55w0rd
      MONGO_INITDB_DATABASE: users
    volumes:
      - mongodb_data_user:/data/db

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: Pa55w0rd
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq

volumes:
  mongodb_data_parcel:
  mongodb_data_user:
  rabbitmq_data:
  rabbitmq_logs:
