server:
  port: 8082

jwt:
  secret: "your_very_long_secret_key_that_is_at_least_32_bytes_long"
  tokenExpire: 60
  refreshTokenExpire: 7

rabbitmq:
  exchange: rabbit_exchange
  registrationQueue: registration_queue
  registrationQueueKey: registration_key
  parcelQueue: parcel_queue
  parcelQueueKey: parcel_key
  userInfoQueue: user_info
  userInfoQueueKey: user_info_key

spring:
  application:
    name: auth-microservice
  data:
    mongodb:
      uri: mongodb://admin:Pa55w0rd@localhost:28018/users?authSource=admin
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: Pa55w0rd