server:
  port: 8083

rabbitmq:
  exchange: rabbit_exchange
  registrationQueue: registration_queue
  registrationQueueKey: registration_key

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: Pa55w0rd